eureka:
  client:
    serviceUrl:
      defaultZone: http://10.16.164.31:8881/eureka/ #可以同时注册到多个eureka上，地址用","隔开


info:                #actuator监控自定义info
  app:
    name: "@project.groupId@"
    description: "@project.artifactId@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.artifactId@"

