eureka:
  client:
    serviceUrl:
      defaultZone: http://10.16.164.31:8881/eureka/ #可以同时注册到多个eureka上，地址用","隔开

server:
  port: 8887

spring:
  application:
    name: zipkin-manager
  datasource:
    schema: classpath:/mysql.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.16.46.170:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    initialize: true #初始化时是否自动创建表
    continueOnError: true
  zipkin:
    enabled: false #关闭zipkin-server自身的链路调用
    storage:
      type: mysql
  sleuth:
    enabled: false #关闭zipkin-server自身的链路调用