server:
  tomcat.uri-encoding: UTF-8
  port: 8881

spring:
  application:
      name: eureka-server
  datasource:
      name: springcloud
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.16.46.191:3306/springcloud?useUnicode=true&characterEncoding=utf-8
      username: root
      password:

mybatis:
  mapper-locations: classpath*:mappers/*.xml

eureka:
  server:
     enable-self-preservation: false          # 开启自我保护模式(eureka server1分钟收到renew的次数小于阈值,会认为是网络问题不会注销任何实例，renew恢复以后退出自我保护模式)
     #renewal-percent-threshold: 0.1          # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
     #eviction-interval-timer-in-ms: 3000     # 设置清理间隔,单位为毫秒,默认为0
  instance:
    hostname: 10.16.164.31
    lease-renewal-interval-in-seconds: 3            #心跳间隔
    lease-expiration-duration-in-seconds: 18        #服务失效时间： 如果多久没有收到请求，则可以删除服务
  client:
    registerWithEureka: false
    fetchRegistry: false
    eureka-service-url-poll-interval-seconds: 60    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    registry-fetch-interval-seconds: 5              # 定义从注册中心获取注册服务的信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #可以同时注册到多个eureka上，地址用","隔开

