eureka:
  client:
    serviceUrl:
      defaultZone: http://10.16.164.31:8881/eureka/ #可以同时注册到多个eureka上，地址用","隔开


server:
  port: 8884

spring:
  application:
    name: service-feign
  zipkin:
    enabled: true
    base-url: http://localhost:8887
  sleuth:
    enabled: true
    sampler:
      percentage: 1  #  默认值为0.1f，现在为了测试设置100%采集

feign:   #开启feign内置的hystrix
  hystrix:
    enabled: true
