server:
  tomcat.uri-encoding: UTF-8
  port: 8882

spring:
  application:
      name: eurekaclient-service-a

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.16.164.31:8881/eureka/ #可以同时注册到多个eureka上，地址用","隔开

management:
   security:
     enabled: false  #关闭actuator安全验证

info:                #actuator监控自定义info
  app:
    name: "@project.groupId@"
    description: "@project.artifactId@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.artifactId@"

